# -*- coding: UTF-8 -*-
# Copyright (C) 2006 Luis Belmar Letelier <luis@itaapy.com>
# Copyright (C) 2006-2008 Hervé Cauwelier <herve@itaapy.com>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.

# Import from itools
from itools.datatypes import Unicode, Boolean

# Import from scrib
from datatypes import Checkboxes, Integer, Decimal
from schema import sum2controle, checkBib


schema = {'field1': (Unicode, ''), 'field2': (Unicode, ''),
          'field3': (Unicode, ''), 'field30': (Unicode, ''),
          'field31': (Unicode, ''), 'field32': (Unicode, ''),
          'field33': (Unicode, ''), 'field4': (Unicode, ''),
          'field5': (Unicode, ''), 'field6': (Unicode, ''),
          'field7': (Unicode, ''), 'field8': (Unicode, ''),
          'field9': (Unicode, ''), 'field10': (Unicode, ''),
          'field11': (Unicode, ''),'field12': (Unicode, ''),
          #
          'fieldA11': (Integer, None), 'fieldA12': (Integer, None),
          'fieldA13': (Integer, None), 'fieldA14': (Integer, None),
          'fieldA15': (Integer, None), 'fieldA16': (Integer, None),
          'fieldA18': (Integer, None),
          'fieldA17': (Integer, None,
                       {'sum': ('fieldA11', 'fieldA12', 'fieldA13',
                                'fieldA14', 'fieldA15', 'fieldA16','fieldA18')}),
          #
          'fieldA21': (Integer, None), 'fieldA22': (Integer, None),
          'fieldA23': (Integer, None),
          'fieldA24': (Integer, None,
                       {'sum': ('fieldA21', 'fieldA22', 'fieldA23')}),
          #
          'fieldA31': (Integer, None, {'depend_field' : ('fieldB32',)}),
          'fieldA32': (Integer, None),
          #

          'fieldB11X': (Integer, None), 'fieldB11Y': (Integer, None),
          'fieldB11Z': (Integer, None, {'sum': ('fieldB11X', 'fieldB11Y')}),
          'fieldB12X': (Integer, None),
          'fieldB12Y': (Integer, None),
          'fieldB12Z': (Integer, None, {'sum': ('fieldB12X', 'fieldB12Y')}),
          'fieldB13X': (Integer, None), 'fieldB13Y': (Integer, None),
          'fieldB13Z': (Integer, None, {'sum': ('fieldB13X', 'fieldB13Y')}),
          'fieldB15': (Boolean, None),
          'fieldB14Z': (Integer, None),
          #
          'fieldB21': (Integer, None), 'fieldB22': (Integer, None),
          'fieldB23': (Integer, None),
          #
          'fieldB31': (Boolean, '', {'depend_field' : ('fieldB32',)} ),
          'fieldB32': (Unicode, ''),
          'fieldB33': (Boolean, '', {'depend_field' : ('fieldB34','fieldB35')}),
          'fieldB34': (Integer, None),
          'fieldB35': (Unicode, ''), 'fieldB36X': (Integer, None),
          'fieldB36Y': (Integer, None), 'fieldB37X': (Integer, None),
          'fieldB37Y': (Integer, None),
          'fieldB38X': (Integer, None, {'sum': ('fieldB36X', 'fieldB37X')}),
          'fieldB38Y': (Integer, None, {'sum': ('fieldB36Y', 'fieldB37Y')}),
          'fieldB40': (Boolean, None),
          'fieldB39': (Boolean, None),
          #
          'fieldB41': (Boolean,'', {'depend_field' : ('fieldB39','fieldB40')}),
          #

          'fieldC11S' : (Integer, None), 'fieldC11T' : (Decimal, None),
          'fieldC11U' : (Integer, None),
          'fieldCV': (Checkboxes, ''),
          'fieldC11W' : (Integer, None), 'fieldC11X' : (Decimal, None),
          'fieldC11Y' : (Integer, None), 'fieldC11Z' : (Integer, None),
          #
          'fieldC12S' : (Integer, None), 'fieldC12T' : (Decimal, None),
          'fieldC12U' : (Integer, None),
          'fieldC12W' : (Integer, None), 'fieldC12X' : (Decimal, None),
          'fieldC12Y' : (Integer, None), 'fieldC12Z' : (Integer, None),
          #
          'fieldC13S' : (Integer, None), 'fieldC13T' : (Decimal, None),
          'fieldC13U' : (Integer, None),
          'fieldC13W' : (Integer, None), 'fieldC13X' : (Decimal, None),
          'fieldC13Y' : (Integer, None), 'fieldC13Z' : (Integer, None),
          #
          'fieldC14S' : (Integer, None), 'fieldC14T' : (Decimal, None),
          'fieldC14U' : (Integer, None),
          'fieldC14W' : (Integer, None), 'fieldC14X' : (Decimal, None),
          'fieldC14Y' : (Integer, None), 'fieldC14Z' : (Integer, None),
          #
          'fieldC17S' : (Integer, None), 'fieldC17T' : (Decimal, None),
          'fieldC17U' : (Integer, None),
          'fieldC17W' : (Integer, None), 'fieldC17X' : (Decimal, None),
          'fieldC17Y' : (Integer, None), 'fieldC17Z' : (Integer, None),
          #
           'fieldC15S' : (Integer, None), 'fieldC15T' : (Decimal, None),
           'fieldC15U' : (Integer, None),
           'fieldC15W' : (Integer, None), 'fieldC15X' : (Decimal, None),
           'fieldC15Y' : (Integer, None), 'fieldC15Z' : (Integer, None),
          #
          #
#           'fieldC16S' : (Integer, None), 'fieldC16T' : (Decimal, None),
#           'fieldC16U' : (Integer, None),
#           'fieldC16W' : (Integer, None), 'fieldC16X' : (Decimal, None),
#           'fieldC16Y' : (Integer, None), 'fieldC16Z' : (Integer, None),
          #
          'fieldC21S' : (Integer, None), 'fieldC21T' : (Decimal, None),
          'fieldC21U' : (Integer, None),
          'fieldC21W' : (Integer, None), 'fieldC21X' : (Decimal, None),
          'fieldC21Y' : (Integer, None), 'fieldC21Z' : (Integer, None),
          #
          'fieldC22S' : (Integer, None), 'fieldC22T' : (Decimal, None),
          'fieldC22U' : (Integer, None),
          'fieldC22W' : (Integer, None), 'fieldC22X' : (Decimal, None),
          'fieldC22Y' : (Integer, None), 'fieldC22Z' : (Integer, None),
          #
          'fieldC23S' : (Integer, None), 'fieldC23T' : (Decimal, None),
          'fieldC23U' : (Integer, None),
          'fieldC23W' : (Integer, None), 'fieldC23X' : (Decimal, None),
          'fieldC23Y' : (Integer, None), 'fieldC23Z' : (Integer, None),
          #
          'fieldC31S' : (Integer, None), 'fieldC31T' : (Decimal, None),
          'fieldC31U' : (Integer, None),
          'fieldC31W' : (Integer, None), 'fieldC31X' : (Decimal, None),
          'fieldC31Y' : (Integer, None), 'fieldC31Z' : (Integer, None),
          #
          'fieldC32S' : (Integer, None), 'fieldC32T' : (Decimal, None),
          'fieldC32U' : (Integer, None),
          'fieldC32W' : (Integer, None), 'fieldC32X' : (Decimal, None),
          'fieldC32Y' : (Integer, None), 'fieldC32Z' : (Integer, None),
          #
          'fieldC33S' : (Integer, None), 'fieldC33T' : (Decimal, None),
          'fieldC33U' : (Integer, None),
          'fieldC33W' : (Integer, None), 'fieldC33X' : (Decimal, None),
          'fieldC33Y' : (Integer, None), 'fieldC33Z' : (Integer, None),
          #
          'fieldC34S' : (Integer, None), 'fieldC34T' : (Decimal, None),
          'fieldC34U' : (Integer, None),
          'fieldC34W' : (Integer, None), 'fieldC34X' : (Decimal, None),
          'fieldC34Y' : (Integer, None), 'fieldC34Z' : (Integer, None),
          #
          'fieldC41S' : (Integer, None),
          'fieldC41U' : (Integer, None),
          'fieldC41W' : (Integer, None),
          'fieldC41Y' : (Integer, None), 'fieldC41Z' : (Integer, None),
          #
          'fieldC42S' : (Integer, None),
          'fieldC42W' : (Integer, None),
          'fieldC42Z' : (Integer, None),
          #
          'fieldC43S' : (Integer, None,
                       {'sum': ('fieldC11S','fieldC12S', 'fieldC13S', 'fieldC14S',
                                 'fieldC15S', 'fieldC21S',
                                'fieldC22S', 'fieldC23S', 'fieldC31S',
                                'fieldC33S', 'fieldC41S', 'fieldC42S')}),
          'fieldC43T' : (Decimal, None,
                        {'sum': ('fieldC11T','fieldC12T', 'fieldC13T', 'fieldC14T',
                                 'fieldC15T', 'fieldC21T',
                                'fieldC22T', 'fieldC23T', 'fieldC31T',
                                'fieldC33T' )}),
          'fieldC43U' : (Integer, None,
                        {'sum': ('fieldC11U','fieldC12U', 'fieldC13U', 'fieldC14U',
                                 'fieldC15U', 'fieldC21U',
                                'fieldC22U', 'fieldC23U', 'fieldC31U',
                                'fieldC33U', 'fieldC41U')}),
          'fieldC43W' : (Integer, None,
                         {'sum': ('fieldC11W','fieldC12W', 'fieldC13W', 'fieldC14W',
                                 'fieldC15W', 'fieldC21W',
                                'fieldC22W', 'fieldC23W', 'fieldC31W',
                                'fieldC33W', 'fieldC41W', 'fieldC42W')}),
          'fieldC43X' : (Decimal, None,
                        {'sum': ('fieldC11X','fieldC12X', 'fieldC13X', 'fieldC14X',
                                 'fieldC15X', 'fieldC21X',
                                'fieldC22X', 'fieldC23X', 'fieldC31X',
                                'fieldC33X'  )}),
          'fieldC43Y' : (Integer, None,
                        {'sum': ('fieldC11Y','fieldC12Y', 'fieldC13Y', 'fieldC14Y',
                                 'fieldC15Y', 'fieldC21Y',
                                'fieldC22Y', 'fieldC23Y', 'fieldC31Y',
                                'fieldC33Y', 'fieldC41Y')}),
          'fieldC43Z' : (Integer, None,
                         {'sum': ('fieldC11Z','fieldC12Z', 'fieldC13Z', 'fieldC14Z',
                                'fieldC15Z', 'fieldC21Z',
                                'fieldC22Z', 'fieldC23Z', 'fieldC31Z',
                                'fieldC33Z', 'fieldC41Z', 'fieldC42Z')}),
          #
          'fieldC51Z' : (Integer, None),
          #

          'fieldD11X' : (Integer, None), 'fieldD11Y' : (Integer, None),
          'fieldD11Z' : (Integer, None,{'sum': ('fieldD11X', 'fieldD11Y')}),
          'fieldD12X' : (Integer, None), 'fieldD12Y' : (Integer, None),
          'fieldD12Z' : (Integer, None,{'sum': ('fieldD12X', 'fieldD12Y')}),
          'fieldD13X' : (Integer, None,{'sum': ('fieldD11X', 'fieldD12X')}),
          'fieldD13Y' : (Integer, None,{'sum': ('fieldD11Y', 'fieldD12Y')}),
          'fieldD13Z' : (Integer, None,{'sum': ('fieldD13X', 'fieldD13Y')}),
          'fieldD14X' : (Integer, None), 'fieldD14Y' : (Integer, None),
          'fieldD14Z' : (Integer, None,{'sum': ('fieldD14X', 'fieldD14Y')}),
          'fieldD15X' : (Integer, None), 'fieldD15Y' : (Integer, None),
          'fieldD15Z' : (Integer, None,{'sum': ('fieldD15X', 'fieldD15Y')}),
          'fieldD16X' : (Integer, None,{'sum': ('fieldD14X', 'fieldD15X')}),
          'fieldD16Y' : (Integer, None,{'sum': ('fieldD14Y', 'fieldD15Y')}),
          'fieldD16Z' : (Integer, None,{'sum': ('fieldD14Z', 'fieldD15Z')}),
          'fieldD17X' : (Integer, None), 'fieldD17Y' : (Integer, None),
          'fieldD17Z' : (Integer, None,{'sum': ('fieldD17X', 'fieldD17Y')}),
          'fieldD18X' : (Integer, None), 'fieldD18Y' : (Integer, None),
          'fieldD18Z' : (Integer, None,{'sum': ('fieldD18X', 'fieldD18Y')}),
          'fieldD19X' : (Integer, None,{'sum': ('fieldD17X', 'fieldD18X')}),
          'fieldD19Y' : (Integer, None,{'sum': ('fieldD17Y', 'fieldD18Y')}),
          'fieldD19Z' : (Integer, None,{'sum': ('fieldD17Z', 'fieldD18Z')}),
          'fieldD20X' : (Integer, None), 'fieldD20Y' : (Integer, None),
          'fieldD20Z' : (Integer, None,{'sum': ('fieldD20X', 'fieldD20Y')}),
          'fieldD21X' : (Integer, None), 'fieldD21Y' : (Integer, None),
          'fieldD21Z' : (Integer, None,{'sum': ('fieldD21X', 'fieldD21Y')}),
          'fieldD22X' : (Integer, None,{'sum': ('fieldD20X', 'fieldD21X')}),
          'fieldD22Y' : (Integer, None,{'sum': ('fieldD20Y', 'fieldD21Y')}),
          'fieldD22Z' : (Integer, None,{'sum': ('fieldD22X', 'fieldD22Y')}),
          'fieldD23X' : (Integer, None), 'fieldD23Y' : (Integer, None),
          'fieldD23Z' : (Integer, None,{'sum': ('fieldD23X', 'fieldD23Y')}),
          'fieldD24X' : (Integer, None), 'fieldD24Y' : (Integer, None),
          'fieldD24Z' : (Integer, None,{'sum': ('fieldD24X', 'fieldD24Y')}),
          'fieldD25X' : (Integer, None), 'fieldD25Y' : (Integer, None),
          'fieldD25Z' : (Integer, None,{'sum': ('fieldD25X', 'fieldD25Y')}),
          'fieldD31' : (Integer, None),
          #
          #'fieldD32' : (Integer, None),
          #
          'fieldE11X' : (Integer, None), 'fieldE11Y' : (Integer, None),
          'fieldE11Z' : (Integer, None,{'sum': ('fieldE11X', 'fieldE11Y')}),
          'fieldE12X' : (Integer, None), 'fieldE12Y' : (Integer, None),
          'fieldE12Z' : (Integer, None,{'sum': ('fieldE12X', 'fieldE12Y')}),
          'fieldE13X' : (Integer, None,{'sum': ('fieldE11X', 'fieldE12X')}),
          'fieldE13Y' : (Integer, None,{'sum': ('fieldE11Y', 'fieldE12Y')}),
          'fieldE13Z' : (Integer, None,{'sum': ('fieldE11Z', 'fieldE12Z')}),
          'fieldE14X' : (Integer, None), 'fieldE14Y' : (Integer, None),
          'fieldE14Z' : (Integer, None,{'sum': ('fieldE14X', 'fieldE14Y')}),
          'fieldE15X' : (Integer, None), 'fieldE15Y' : (Integer, None),
          'fieldE15Z' : (Integer, None,{'sum': ('fieldE15X', 'fieldE15Y')}),
          'fieldE16X' : (Integer, None,{'sum': ('fieldE14X', 'fieldE15X')}),
          'fieldE16Y' : (Integer, None,{'sum': ('fieldE14Y', 'fieldE15Y')}),
          'fieldE16Z' : (Integer, None,{'sum': ('fieldE16X', 'fieldE16Y')}),
          'fieldE17X' : (Integer, None), 'fieldE17Y' : (Integer, None),
          'fieldE17Z' : (Integer, None,{'sum': ('fieldE17X', 'fieldE17Y')}),
          'fieldE18X' : (Integer, None), 'fieldE18Y' : (Integer, None),
          'fieldE18Z' : (Integer, None,{'sum': ('fieldE18X', 'fieldE18Y')}),
          'fieldE19X' : (Integer, None,{'sum': ('fieldE17X', 'fieldE18X')}),
          'fieldE19Y' : (Integer, None,{'sum': ('fieldE17Y', 'fieldE18Y')}),
          'fieldE19Z' : (Integer, None,{'sum': ('fieldE19X', 'fieldE19Y')}),
          'fieldE20X' : (Integer, None), 'fieldE20Y' : (Integer, None),
          'fieldE20Z' : (Integer, None,{'sum': ('fieldE20X', 'fieldE20Y')}),
          'fieldE21X' : (Integer, None), 'fieldE21Y' : (Integer, None),
          'fieldE21Z' : (Integer, None,{'sum': ('fieldE21X', 'fieldE21Y')}),
          'fieldE22X' : (Integer, None,{'sum': ('fieldE20X', 'fieldE21X')}) ,
          'fieldE22Y' : (Integer, None,{'sum': ('fieldE20Y', 'fieldE21Y')}),
          'fieldE22Z' : (Integer, None,{'sum': ('fieldE22X', 'fieldE22Y')}),
          'fieldE23X' : (Integer, None), 'fieldE23Y' : (Integer, None),
          'fieldE23Z' : (Integer, None,{'sum': ('fieldE23X', 'fieldE23Y')}),
          'fieldE24X' : (Integer, None), 'fieldE24Y' : (Integer, None),
          'fieldE24Z' : (Integer, None,{'sum': ('fieldE24X', 'fieldE24Y')}),
          #
          'fieldE31X' : (Integer, None), 'fieldE31Y' : (Integer, None),
          'fieldE31Z' : (Integer, None,{'sum': ('fieldE31X', 'fieldE31Y')}),
          'fieldE32X' : (Integer, None), 'fieldE32Y' : (Integer, None),
          'fieldE32Z' : (Integer, None,{'sum': ('fieldE32X', 'fieldE32Y')}),
          'fieldE33X' : (Integer, None,{'sum': ('fieldE31X', 'fieldE32X')}),
          'fieldE33Y' : (Integer, None,{'sum': ('fieldE31Y', 'fieldE32Y')}),
          'fieldE33Z' : (Integer, None,{'sum': ('fieldE33X', 'fieldE33Y')}),
          'fieldE34X' : (Integer, None), 'fieldE34Y' : (Integer, None),
          'fieldE34Z' : (Integer, None,{'sum': ('fieldE34X', 'fieldE34Y')}),
          'fieldE35X' : (Integer, None), 'fieldE35Y' : (Integer, None),
          'fieldE35Z' : (Integer, None,{'sum': ('fieldE35X', 'fieldE35Y')}),
          'fieldE36X' : (Integer, None,{'sum': ('fieldE34X', 'fieldE35X')}),
          'fieldE36Y' : (Integer, None,{'sum': ('fieldE34Y', 'fieldE35Y')}),
          'fieldE36Z' : (Integer, None,{'sum': ('fieldE34Z', 'fieldE35Z')}),
          'fieldE37X' : (Integer, None), 'fieldE37Y' : (Integer, None),
          'fieldE37Z' : (Integer, None,{'sum': ('fieldE37X', 'fieldE37Y')}),
          'fieldE38X' : (Integer, None), 'fieldE38Y' : (Integer, None),
          'fieldE38Z' : (Integer, None,{'sum': ('fieldE38X', 'fieldE38Y')}),
          'fieldE39X' : (Integer, None,{'sum': ('fieldE37X', 'fieldE38X')}),
          'fieldE39Y' : (Integer, None,{'sum': ('fieldE37Y', 'fieldE38Y')}),
          'fieldE39Z' : (Integer, None,{'sum': ('fieldE39X', 'fieldE39Y')}),
          'fieldE40X' : (Integer, None), 'fieldE40Y' : (Integer, None),
          'fieldE40Z' : (Integer, None,{'sum': ('fieldE40X', 'fieldE40Y')}),
          'fieldE41X' : (Integer, None), 'fieldE41Y' : (Integer, None),
          'fieldE41Z' : (Integer, None,{'sum': ('fieldE41X', 'fieldE41Y')}),
          'fieldE42X' : (Integer, None,{'sum': ('fieldE40X', 'fieldE41X')}),
          'fieldE42Y' : (Integer, None,{'sum': ('fieldE40Y', 'fieldE41Y')}),
          'fieldE42Z' : (Integer, None,{'sum': ('fieldE42X', 'fieldE42Y')}),
          'fieldE43X' : (Integer, None), 'fieldE43Y' : (Integer, None),
          'fieldE43Z' : (Integer, None,{'sum': ('fieldE43X', 'fieldE43Y')}),
          'fieldE44X' : (Integer, None), 'fieldE44Y' : (Integer, None),
          'fieldE44Z' : (Integer, None,{'sum': ('fieldE44X', 'fieldE44Y')}),
          #
          'fieldE51X' : (Integer, None), 'fieldE51Y' : (Integer, None),
          'fieldE51Z' : (Integer, None,{'sum': ('fieldE51X', 'fieldE51Y')}),
          'fieldE52X' : (Integer, None), 'fieldE52Y' : (Integer, None),
          'fieldE52Z' : (Integer, None,{'sum': ('fieldE52X', 'fieldE52Y')}),
          'fieldE53X' : (Integer, None,{'sum': ('fieldE51X', 'fieldE52X')}),
          'fieldE53Y' : (Integer, None,{'sum': ('fieldE51Y', 'fieldE52Y')}),
          'fieldE53Z' : (Integer, None,{'sum': ('fieldE51Z', 'fieldE52Z')}),
          'fieldE54X' : (Integer, None), 'fieldE54Y' : (Integer, None),
          'fieldE54Z' : (Integer, None,{'sum': ('fieldE54X', 'fieldE54Y')}),
          'fieldE55X' : (Integer, None), 'fieldE55Y' : (Integer, None),
          'fieldE55Z' : (Integer, None,{'sum': ('fieldE55X', 'fieldE55Y')}),
          'fieldE56X' : (Integer, None,{'sum': ('fieldE54X', 'fieldE55X')}),
          'fieldE56Y' : (Integer, None,{'sum': ('fieldE54Y', 'fieldE55Y')}),
          'fieldE56Z' : (Integer, None,{'sum': ('fieldE54Z', 'fieldE55Z')}),
          'fieldE57X' : (Integer, None), 'fieldE57Y' : (Integer, None),
          'fieldE57Z' : (Integer, None,{'sum': ('fieldE57X', 'fieldE57Y')}),
          'fieldE58X' : (Integer, None), 'fieldE58Y' : (Integer, None),
          'fieldE58Z' : (Integer, None,{'sum': ('fieldE58X', 'fieldE58Y')}),
          'fieldE59X' : (Integer, None,{'sum': ('fieldE57X', 'fieldE58X')}),
          'fieldE59Y' : (Integer, None,{'sum': ('fieldE57Y', 'fieldE58Y')}),
          'fieldE59Z' : (Integer, None,{'sum': ('fieldE59X', 'fieldE59Y')}),
          'fieldE60X' : (Integer, None), 'fieldE60Y' : (Integer, None),
          'fieldE60Z' : (Integer, None,{'sum': ('fieldE60X', 'fieldE60Y')}),
          'fieldE61X' : (Integer, None), 'fieldE61Y' : (Integer, None),
          'fieldE61Z' : (Integer, None,{'sum': ('fieldE61X', 'fieldE61Y')}),
          'fieldE62X' : (Integer, None,{'sum': ('fieldE60X', 'fieldE61X')}),
          'fieldE62Y' : (Integer, None,{'sum': ('fieldE60Y', 'fieldE61Y')}),
          'fieldE62Z' : (Integer, None,{'sum': ('fieldE62X', 'fieldE62Y')}),
          'fieldE63X' : (Integer, None), 'fieldE63Y' : (Integer, None),
          'fieldE63Z' : (Integer, None,{'sum': ('fieldE63X', 'fieldE63Y')}),
          'fieldE64X' : (Integer, None), 'fieldE64Y' : (Integer, None),
          'fieldE64Z' : (Integer, None,{'sum': ('fieldE64X', 'fieldE64Y')}),
          #
          'fieldE71X' : (Integer, None), 'fieldE71Y' : (Integer, None),
          'fieldE71Z' : (Integer, None,{'sum': ('fieldE71X', 'fieldE71Y')}),
          'fieldE72X' : (Integer, None), 'fieldE72Y' : (Integer, None),
          'fieldE72Z' : (Integer, None,{'sum': ('fieldE72X', 'fieldE72Y')}),
          'fieldE73X' : (Integer, None), 'fieldE73Y' : (Integer, None),
          'fieldE73Z' : (Integer, None,{'sum': ('fieldE73X', 'fieldE73Y')}),
          #
          'fieldE81X' : (Integer, None), 'fieldE81Y' : (Integer, None),
          'fieldE81Z' : (Integer, None,{'sum': ('fieldE81X', 'fieldE81Y')}),
          'fieldE82X' : (Integer, None), 'fieldE82Y' : (Integer, None),
          'fieldE82Z' : (Integer, None,{'sum': ('fieldE82X', 'fieldE82Y')}),
          #
          'fieldE83X' : (Integer, None), 'fieldE83Y' : (Integer, None),
          'fieldE83Z' : (Integer, None,{'sum': ('fieldE83X', 'fieldE83Y')}),
          'fieldE84X' : (Integer, None), 'fieldE84Y' : (Integer, None),
          'fieldE84Z' : (Integer, None,{'sum': ('fieldE84X', 'fieldE84Y')}),
          'fieldE85X' : (Integer, None,{'sum': ('fieldE83X', 'fieldE84X')}),
          'fieldE85Y' : (Integer, None,{'sum': ('fieldE83Y', 'fieldE84Y')}),
          'fieldE85Z' : (Integer, None,{'sum': ('fieldE85X', 'fieldE85Y')}),
          'fieldE86X' : (Integer, None), 'fieldE86Y' : (Integer, None),
          'fieldE86Z' : (Integer, None,{'sum': ('fieldE86X', 'fieldE86Y')}),
          'fieldE87X' : (Integer, None), 'fieldE87Y' : (Integer, None),
          'fieldE87Z' : (Integer, None,{'sum': ('fieldE87X', 'fieldE87Y')}),
          'fieldE88X' : (Integer, None,{'sum': ('fieldE86X', 'fieldE87X')}),
          'fieldE88Y' : (Integer, None,{'sum': ('fieldE86Y', 'fieldE87Y')}),
          'fieldE88Z' : (Integer, None,{'sum': ('fieldE86Z', 'fieldE87Z')}),
          'fieldE89X' : (Integer, None), 'fieldE89Y' : (Integer, None),
          'fieldE89Z' : (Integer, None,{'sum': ('fieldE89X', 'fieldE89Y')}),
          'fieldE90X' : (Integer, None), 'fieldE90Y' : (Integer, None),
          'fieldE90Z' : (Integer, None,{'sum': ('fieldE90X', 'fieldE90Y')}),
          'fieldE91X' : (Integer, None,{'sum': ('fieldE89X', 'fieldE90X')}),
          'fieldE91Y' : (Integer, None,{'sum': ('fieldE89Y', 'fieldE90Y')}),
          'fieldE91Z' : (Integer, None,{'sum': ('fieldE89Z', 'fieldE90Z')}),
          'fieldE92X' : (Integer, None), 'fieldE92Y' : (Integer, None),
          'fieldE92Z' : (Integer, None,{'sum': ('fieldE92X', 'fieldE92Y')}),
          'fieldE93X' : (Integer, None), 'fieldE93Y' : (Integer, None),
          'fieldE93Z' : (Integer, None,{'sum': ('fieldE93X', 'fieldE93Y')}),
          'fieldE94X' : (Integer, None,{'sum': ('fieldE92X', 'fieldE93X')}),
          'fieldE94Y' : (Integer, None,{'sum': ('fieldE92Y', 'fieldE93Y')}),
          'fieldE94Z' : (Integer, None,{'sum': ('fieldE92Z', 'fieldE93Z')}),
          'fieldE95X' : (Integer, None), 'fieldE95Y' : (Integer, None),
          'fieldE95Z' : (Integer, None,{'sum': ('fieldE95X', 'fieldE95Y')}),
          'fieldE96X' : (Integer, None), 'fieldE96Y' : (Integer, None),
          'fieldE96Z' : (Integer, None,{'sum': ('fieldE96X', 'fieldE96Y')}),
          'fieldE97X' : (Integer, None), 'fieldE97Y' : (Integer, None),
          'fieldE97Z' : (Integer, None,{'sum': ('fieldE97X', 'fieldE97Y')}),
          'fieldE99X' : (Integer, None), 'fieldE99Y' : (Integer, None),
          'fieldE99Z' : (Integer, None,{'sum': ('fieldE99X', 'fieldE99Y')}),
          'fieldE98X' : (Integer, None,{'sum': ('fieldE85X', 'fieldE88X','fieldE91X', 'fieldE94X','fieldE95X', 'fieldE96X','fieldE97X')}),
          'fieldE98Y' : (Integer, None,{'sum': ('fieldE85Y', 'fieldE88Y','fieldE91Y', 'fieldE94Y','fieldE95Y', 'fieldE96Y','fieldE97Y')}),
          'fieldE98Z' : (Integer, None,{'sum': ('fieldE98X', 'fieldE98Y')}),
          #

          'fieldF11W' : (Integer, None), 'fieldF11X' : (Integer, None),
          'fieldF11Y' : (Integer, None),
          'fieldF12W' : (Integer, None), 'fieldF12X' : (Integer, None),
          'fieldF12Y' : (Integer, None),
          'fieldF13W' : (Integer, None), 'fieldF13X' : (Integer, None),
          'fieldF13Y' : (Integer, None),
          'fieldF14W' : (Integer, None), 'fieldF14X' : (Integer, None),
          'fieldF14Y' : (Integer, None),
          'fieldF15W' : (Integer, None), 'fieldF15X' : (Integer, None),
          'fieldF15Y' : (Integer, None),
          'fieldF16W' : (Integer, None,{'sum': ('fieldF11W', 'fieldF12W','fieldF13W', 'fieldF14W','fieldF15W')}),
          'fieldF16X' : (Integer, None,{'sum': ('fieldF11X', 'fieldF12X','fieldF13X', 'fieldF14X','fieldF15X')}),
          'fieldF16Y' : (Integer, None,{'sum': ('fieldF11Y', 'fieldF12Y','fieldF13Y', 'fieldF14Y','fieldF15Y')}),
          'fieldF17W' : (Integer, None), 'fieldF17X' : (Integer, None),
          'fieldF17Y' : (Integer, None),
          'fieldF18W' : (Integer, None,{'sum': ('fieldF16W', 'fieldF17W')}),
          'fieldF18X' : (Integer, None,{'sum': ('fieldF16X', 'fieldF17X')}),
          'fieldF18Y' : (Integer, None,{'sum': ('fieldF16Y', 'fieldF17Y')}),
          'fieldF19X' : (Integer, None), 'fieldF19Y' : (Integer, None),
          'fieldF20X' : (Integer, None), 'fieldF20Y' : (Integer, None),
          'fieldF21X' : (Integer, None), 'fieldF21Y' : (Integer, None),
          #
          'fieldF31Y' : (Integer, None), 'fieldF31Z' : (Integer, None),
          'fieldF32Y' : (Integer, None), 'fieldF32Z' : (Integer, None),
          'fieldF33Y' : (Integer, None,{'sum': ('fieldF31Y', 'fieldF32Y')}),
          'fieldF33Z' : (Integer, None,{'sum': ('fieldF31Z', 'fieldF32Z')}),
          'fieldF34Y' : (Integer, None), 'fieldF34Z' : (Integer, None),
          'fieldF35Y' : (Integer, None), 'fieldF35Z' : (Integer, None),
          'fieldF36Y' : (Integer, None), 'fieldF36Z' : (Integer, None),
          'fieldF37Y' : (Integer, None), 'fieldF37Z' : (Integer, None),
          'fieldF38Y' : (Integer, None,{'sum': ('fieldF33Y', 'fieldF34Y','fieldF35Y', 'fieldF36Y','fieldF37Y')}),
          'fieldF38Z' : (Integer, None,{'sum': ('fieldF33Z', 'fieldF34Z','fieldF35Z', 'fieldF36Z','fieldF37Z')}),
          #
          'fieldF41W' : (Integer, None), 'fieldF41X' : (Integer, None),
          'fieldF41Y' : (Integer, None),
          'fieldF42W' : (Integer, None), 'fieldF42X' : (Integer, None),
          'fieldF42Y' : (Integer, None),
          'fieldF43W' : (Integer, None), 'fieldF43X' : (Integer, None),
          'fieldF43Y' : (Integer, None),
          'fieldF44W' : (Integer, None), 'fieldF44X' : (Integer, None),
          'fieldF44Y' : (Integer, None),
          'fieldF45W' : (Integer, None), 'fieldF45X' : (Integer, None),
          'fieldF45Y' : (Integer, None),
          'fieldF46W' : (Integer, None,{'sum': ('fieldF41W', 'fieldF42W','fieldF43W', 'fieldF44W','fieldF45W')}),
          'fieldF46X' : (Integer, None,{'sum': ('fieldF41X', 'fieldF42X','fieldF43X', 'fieldF44X','fieldF45X')}),
          'fieldF46Y' : (Integer, None,{'sum': ('fieldF41Y', 'fieldF42Y','fieldF43Y', 'fieldF44Y','fieldF45Y')}),
          #
          'fieldF51W' : (Integer, None), 'fieldF51X' : (Integer, None),
          'fieldF51Y' : (Integer, None),
          'fieldF51Z' : (Integer, None,{'sum': ('fieldF51W', 'fieldF51X','fieldF51Y')}),
          'fieldF52W' : (Integer, None), 'fieldF52X' : (Integer, None),
          'fieldF52Y' : (Integer, None),
          'fieldF52Z' : (Integer, None,{'sum': ('fieldF52W', 'fieldF52X','fieldF52Y')}),
          'fieldF53W' : (Integer, None), 'fieldF53X' : (Integer, None),
          'fieldF53Y' : (Integer, None),
          'fieldF53Z' : (Integer, None,{'sum': ('fieldF53W', 'fieldF53X','fieldF53Y')}),
          'fieldF54W' : (Integer, None), 'fieldF54X' : (Integer, None),
          'fieldF54Y' : (Integer, None),
          'fieldF54Z' : (Integer, None,{'sum': ('fieldF54W', 'fieldF54X','fieldF54Y')}),
          'fieldF55W' : (Integer, None,{'sum': ('fieldF52W', 'fieldF53W','fieldF54W')}),
          'fieldF55X' : (Integer, None,{'sum': ('fieldF52X', 'fieldF53X','fieldF54X')}),
          'fieldF55Y' : (Integer, None,{'sum': ('fieldF52Y', 'fieldF53Y','fieldF54Y')}),
          'fieldF55Z' : (Integer, None,{'sum': ('fieldF55W', 'fieldF55X', 'fieldF55Y')}),
          'fieldF56W' : (Integer, None,{'sum': ('fieldF51W', 'fieldF55W')}),
          'fieldF56X' : (Integer, None,{'sum': ('fieldF51X', 'fieldF55X')}),
          'fieldF56Y' : (Integer, None,{'sum': ('fieldF51Y', 'fieldF55Y')}),
          'fieldF56Z' : (Integer, None,{'sum': ('fieldF56W', 'fieldF56X','fieldF56Y')}),
          #
          'fieldF61W' : (Integer, None), 'fieldF61X' : (Integer, None),
          'fieldF61Y' : (Integer, None),
          'fieldF61Z' : (Integer, None,{'sum': ('fieldF61W', 'fieldF61X','fieldF61Y')}),
          'fieldF62W' : (Integer, None), 'fieldF62X' : (Integer, None),
          'fieldF62Y' : (Integer, None),
          'fieldF62Z' : (Integer, None,{'sum': ('fieldF62W', 'fieldF62X','fieldF62Y')}),
          'fieldF63W' : (Integer, None,{'sum': ('fieldF61W', 'fieldF62W')}),
          'fieldF63X' : (Integer, None,{'sum': ('fieldF61X', 'fieldF62X')}),
          'fieldF63Y' : (Integer, None,{'sum': ('fieldF61Y', 'fieldF62Y')}),
          'fieldF63Z' : (Integer, None,{'sum': ('fieldF61Z', 'fieldF62Z')}),
          'fieldF64W' : (Integer, None), 'fieldF64X' : (Integer, None),
          'fieldF64Y' : (Integer, None),
          'fieldF64Z' : (Integer, None,{'sum': ('fieldF64W', 'fieldF64X','fieldF64Y')}),
          'fieldF65W' : (Integer, None), 'fieldF65X' : (Integer, None),
          'fieldF65Y' : (Integer, None),
          'fieldF65Z' : (Integer, None,{'sum': ('fieldF65W', 'fieldF65X','fieldF65Y')}),
          'fieldF66W' : (Integer, None), 'fieldF66X' : (Integer, None),
          'fieldF66Y' : (Integer, None),
          'fieldF66Z' : (Integer, None,{'sum': ('fieldF66W', 'fieldF66X','fieldF66Y')}),
          'fieldF67W' : (Integer, None), 'fieldF67X' : (Integer, None),
          'fieldF67Y' : (Integer, None),
          'fieldF67Z' : (Integer, None,{'sum': ('fieldF67W', 'fieldF67X','fieldF67Y')}),
          'fieldF68W' : (Integer, None), 'fieldF68X' : (Integer, None),
          'fieldF68Y' : (Integer, None),
          'fieldF68Z' : (Integer, None,{'sum': ('fieldF68W', 'fieldF68X','fieldF68Y')}),
          'fieldF69W' : (Integer, None,{'sum': ('fieldF63W', 'fieldF64W','fieldF65W','fieldF66W', 'fieldF67W','fieldF68W')}),
          'fieldF69X' : (Integer, None,{'sum': ('fieldF63X', 'fieldF64X','fieldF65X','fieldF66X', 'fieldF67X','fieldF68X')}),
          'fieldF69Y' : (Integer, None,{'sum': ('fieldF63Y', 'fieldF64Y','fieldF65Y','fieldF66Y', 'fieldF67Y','fieldF68Y')}),
          'fieldF69Z' : (Integer, None,{'sum': ('fieldF69W', 'fieldF69X','fieldF69Y')}),
          #

          'fieldG11V' : (Integer, None), 'fieldG11W' : (Integer, None),
          'fieldG11X' : (Integer, None), 'fieldG11Y' : (Integer, None),
          'fieldG11Z' : (Integer, None),
          'fieldG12V' : (Integer, None), 'fieldG12W' : (Integer, None),
          'fieldG12X' : (Integer, None), 'fieldG12Y' : (Integer, None),
          'fieldG12Z' : (Integer, None),
          'fieldG13V' : (Integer, None), 'fieldG13W' : (Integer, None),
          'fieldG13X' : (Integer, None), 'fieldG13Y' : (Integer, None),
          'fieldG13Z' : (Integer, None),
          'fieldG14V' : (Integer, None), 'fieldG14W' : (Integer, None),
          'fieldG14X' : (Integer, None), 'fieldG14Y' : (Integer, None),
          'fieldG14Z' : (Integer, None),
          'fieldG15V' : (Integer, None), 'fieldG15W' : (Integer, None),
          'fieldG15X' : (Integer, None), 'fieldG15Y' : (Integer, None),
          'fieldG15Z' : (Integer, None),
          'fieldG16V' : (Integer, None), 'fieldG16W' : (Integer, None),
          'fieldG16X' : (Integer, None), 'fieldG16Y' : (Integer, None),
          'fieldG16Z' : (Integer, None),
          'fieldG17V' : (Integer, None), 'fieldG17W' : (Integer, None),
          'fieldG17X' : (Integer, None), 'fieldG17Y' : (Integer, None),
          'fieldG17Z' : (Integer, None),
          'fieldG18V' : (Integer, None), 'fieldG18W' : (Integer, None),
          'fieldG18X' : (Integer, None), 'fieldG18Y' : (Integer, None),
          'fieldG18Z' : (Integer, None),
          'fieldG19V' : (Integer, None), 'fieldG19W' : (Integer, None),
          'fieldG19X' : (Integer, None), 'fieldG19Y' : (Integer, None),
          'fieldG19Z' : (Integer, None),
          'fieldG20V' : (Integer, None), 'fieldG20W' : (Integer, None),
          'fieldG20X' : (Integer, None), 'fieldG20Y' : (Integer, None),
          'fieldG20Z' : (Integer, None),
          'fieldG21V' : (Integer, None), 'fieldG21W' : (Integer, None),
          'fieldG21X' : (Integer, None), 'fieldG21Y' : (Integer, None),
          'fieldG21Z' : (Integer, None),
          'fieldG22V' : (Integer, None,{'sum': ('fieldG11V', 'fieldG12V','fieldG13V', 'fieldG14V','fieldG15V',
                                                'fieldG16V', 'fieldG17V','fieldG18V', 'fieldG19V','fieldG20V','fieldG21V')}),
          'fieldG22W' : (Integer, None,{'sum': ('fieldG11W', 'fieldG12W','fieldG13W', 'fieldG14W','fieldG15W',
                                                'fieldG16W', 'fieldG17W','fieldG18W', 'fieldG19W','fieldG20W','fieldG21W')}),
          'fieldG22X' : (Integer, None,{'sum': ('fieldG11X', 'fieldG12X','fieldG13X', 'fieldG14X','fieldG15X',
                                                'fieldG16X', 'fieldG17X','fieldG18X', 'fieldG19X','fieldG20X','fieldG21X')}),
          'fieldG22Y' : (Integer, None,{'sum': ('fieldG11Y', 'fieldG12Y','fieldG13Y', 'fieldG14Y','fieldG15Y',
                                                'fieldG16Y', 'fieldG17Y','fieldG18Y', 'fieldG19Y','fieldG20Y','fieldG21Y')}),
          'fieldG22Z' : (Integer, None,{'sum': ('fieldG11Z', 'fieldG12Z','fieldG13Z', 'fieldG14Z','fieldG15Z',
                                                'fieldG16Z', 'fieldG17Z','fieldG18Z', 'fieldG19Z','fieldG20Z','fieldG21Z')}),
          #
          'fieldG31X' : (Integer, None), 'fieldG31Y' : (Integer, None),
          'fieldG31Z' : (Integer, None),
          'fieldG32X' : (Integer, None), 'fieldG32Y' : (Integer, None),
          'fieldG32Z' : (Integer, None),
          'fieldG33X' : (Integer, None), 'fieldG33Y' : (Integer, None),
          'fieldG33Z' : (Integer, None),
          'fieldG34X' : (Integer, None), 'fieldG34Y' : (Integer, None),
          'fieldG34Z' : (Integer, None),
          'fieldG35X' : (Integer, None), 'fieldG35Y' : (Integer, None),
          'fieldG35Z' : (Integer, None),
          'fieldG36X' : (Integer, None), 'fieldG36Y' : (Integer, None),
          'fieldG36Z' : (Integer, None),
          'fieldG37X' : (Integer, None), 'fieldG37Y' : (Integer, None),
          'fieldG37Z' : (Integer, None),
          'fieldG38X' : (Integer, None), 'fieldG38Y' : (Integer, None),
          'fieldG38Z' : (Integer, None),
          'fieldG39X' : (Integer, None), 'fieldG39Y' : (Integer, None),
          'fieldG39Z' : (Integer, None),
          'fieldG40X' : (Integer, None), 'fieldG40Y' : (Integer, None),
          'fieldG40Z' : (Integer, None),
          'fieldG41X' : (Integer, None), 'fieldG41Y' : (Integer, None),
          'fieldG41Z' : (Integer, None),
          'fieldG42X' : (Integer, None,{'sum': ('fieldG31X', 'fieldG32X','fieldG33X', 'fieldG34X','fieldG35X',
                                                'fieldG36X', 'fieldG37X','fieldG38X', 'fieldG39X','fieldG40X','fieldG41X')}),
          'fieldG42Y' : (Integer, None,{'sum': ('fieldG31Y', 'fieldG32Y','fieldG33Y', 'fieldG34Y','fieldG35Y',
                                                'fieldG36Y', 'fieldG37Y','fieldG38Y', 'fieldG39Y','fieldG40Y','fieldG41Y')}),
          'fieldG42Z' : (Integer, None,{'sum': ('fieldG31Z', 'fieldG32Z','fieldG33Z', 'fieldG34Z','fieldG35Z',
                                                'fieldG36Z', 'fieldG37Z','fieldG38Z', 'fieldG39Z','fieldG40Z','fieldG41Z')}),
          #
          'fieldH11': (Boolean, '', {'depend_field' : ('fieldH12',
                                                          'fieldH13',
                                                          'fieldH14',
                                                          'fieldH15',
                                                          'fieldH16',
                                                          'fieldH17',
                                                          'fieldH18','fieldH19')}),
          'fieldH12': (Boolean, ''),
          'fieldH13': (Boolean, ''), 'fieldH14': (Boolean, ''),
          'fieldH15': (Boolean, ''), 'fieldH16': (Boolean, ''),
          'fieldH19': (Unicode, None),
          'fieldH17' : (Integer, None), 'fieldH18' : (Integer, None),
          #
          'fieldH21': (Boolean, '', {'depend_field' : ('fieldH22',)}),
          'fieldH22': (Unicode, None),
          'fieldH23': (Boolean, '', {'depend_field' : ('fieldH24',)}),
          'fieldH24': (Unicode, None),
          'fieldH25': (Boolean, '', {'depend_field' : ('fieldH26',)}),
          'fieldH26': (Unicode, None),
          'fieldH27': (Boolean, '', {'depend_field' : ('fieldH28',
                                                              'fieldH29')}),
          'fieldH28': (Boolean, ''),
          'fieldH29': (Boolean, ''),
          'fieldH30': (Unicode, None),
          #
          'fieldH75': (Boolean, '', {'depend_field' : ('fieldH76')}),
          'fieldH76': (Unicode, None),
          'fieldH31V' : (Boolean, '', {'depend_field' : ('fieldH31W','fieldH31X','fieldH31Y','fieldH31Z')}),
          'fieldH31W' : (Integer, None),
          'fieldH31X' : (Integer, None), 'fieldH31Y' : (Integer, None),
          'fieldH31Z' : (Integer, None),
          'fieldH32V' : (Boolean, '', {'depend_field' : ('fieldH32W','fieldH32X','fieldH32Y','fieldH32Z')}),
          'fieldH32W' : (Integer, None),
          'fieldH32X' : (Integer, None), 'fieldH32Y' : (Integer, None),
          'fieldH32Z' : (Integer, None),
          'fieldH33V' : (Boolean, '', {'depend_field' : ('fieldH33W','fieldH33X','fieldH33Y','fieldH33Z')}),
          'fieldH33W' : (Integer, None),
          'fieldH33X' : (Integer, None), 'fieldH33Y' : (Integer, None),
          'fieldH33Z' : (Integer, None),
          'fieldH34V' : (Boolean, '', {'depend_field' : ('fieldH34W','fieldH34X','fieldH34Y','fieldH34Z')}),
          'fieldH34W' : (Integer, None),
          'fieldH34X' : (Integer, None), 'fieldH34Y' : (Integer, None),
          'fieldH34Z' : (Integer, None),
          'fieldH35V' : (Boolean, '', {'depend_field' : ('fieldH35W','fieldH35X','fieldH35Y','fieldH35Z')}),
          'fieldH35W' : (Integer, None),
          'fieldH35X' : (Integer, None), 'fieldH35Y' : (Integer, None),
          'fieldH35Z' : (Integer, None),
          'fieldH77V' : (Boolean, '', {'depend_field' : ('fieldH77W','fieldH77X','fieldH77Y','fieldH77Z')}),
          'fieldH77W' : (Integer, None),
          'fieldH77X' : (Integer, None), 'fieldH77Y' : (Integer, None),
          'fieldH77Z' : (Integer, None),
          'fieldH78V' : (Boolean, '', {'depend_field' : ('fieldH78W','fieldH78X','fieldH78Y','fieldH78Z')}),
          'fieldH78W' : (Integer, None),
          'fieldH78X' : (Integer, None), 'fieldH78Y' : (Integer, None),
          'fieldH78Z' : (Integer, None),
          'fieldH36V' : (Boolean, '', {'depend_field' : ('fieldH36W','fieldH36X','fieldH36Y','fieldH36Z')}),
          'fieldH36W' : (Integer, None),
          'fieldH36X' : (Integer, None), 'fieldH36Y' : (Integer, None),
          'fieldH36Z' : (Integer, None),
          'fieldH37V' : (Boolean, '', {'depend_field' : ('fieldH37W','fieldH37X','fieldH37Y','fieldH37Z')}),
          'fieldH37W' : (Integer, None),
          'fieldH37X' : (Integer, None), 'fieldH37Y' : (Integer, None),
          'fieldH37Z' : (Integer, None),
          'fieldH38V' : (Boolean, '', {'depend_field' : ('fieldH38W','fieldH38X','fieldH38Y','fieldH38Z')}),
          'fieldH38W' : (Integer, None),
          'fieldH38X' : (Integer, None), 'fieldH38Y' : (Integer, None),
          'fieldH38Z' : (Integer, None),
          'fieldH39V' : (Boolean, '', {'depend_field' : ('fieldH39W','fieldH39X','fieldH39Y','fieldH39Z')}),
          'fieldH39W' : (Integer, None),
          'fieldH39X' : (Integer, None), 'fieldH39Y' : (Integer, None),
          'fieldH39Z' : (Integer, None),
          #
          'fieldH41X' : (Boolean, '', {'depend_field' : ('fieldH41Y','fieldH41Z')}), 'fieldH41Y' : (Integer, None),
          'fieldH41Z' : (Integer, None),
          'fieldH42X' : (Boolean, '', {'depend_field' : ('fieldH42Y','fieldH42Z')}), 'fieldH42Y' : (Integer, None),
          'fieldH42Z' : (Integer, None),
          'fieldH43X' : (Boolean, '', {'depend_field' : ('fieldH43Y','fieldH43Z')}), 'fieldH43Y' : (Integer, None),
          'fieldH43Z' : (Integer, None),
          'fieldH44X' : (Boolean, '', {'depend_field' : ('fieldH44Y','fieldH44Z')}), 'fieldH44Y' : (Integer, None),
          'fieldH44Z' : (Integer, None),
          'fieldH45X' : (Boolean, '', {'depend_field' : ('fieldH45Y','fieldH45Z')}), 'fieldH45Y' : (Integer, None),
          'fieldH45Z' : (Integer, None),
          'fieldH46X' : (Boolean, '', {'depend_field' : ('fieldH46Y','fieldH46Z')}), 'fieldH46Y' : (Integer, None),
          'fieldH46Z' : (Integer, None),
          'fieldH47X' : (Boolean, '', {'depend_field' : ('fieldH47Y','fieldH47Z')}), 'fieldH47Y' : (Integer, None),
          'fieldH47Z' : (Integer, None),
          'fieldH79X' : (Boolean, '', {'depend_field' : ('fieldH79Y','fieldH79Z')}), 'fieldH79Y' : (Integer, None),
          'fieldH79Z' : (Integer, None),
          'fieldH48X' : (Boolean, '', {'depend_field' : ('fieldH48Y','fieldH48Z')}), 'fieldH48Y' : (Integer, None),
          'fieldH48Z' : (Integer, None),
          'fieldH49X' : (Boolean, '', {'depend_field' : ('fieldH49Y','fieldH49Z')}), 'fieldH49Y' : (Integer, None),
          'fieldH49Z' : (Integer, None),
          #
          'fieldH51':   (Boolean, '', {'depend_field' : ('fieldH52','fieldH53')}),
          'fieldH52' : (Integer, None),
          'fieldH53' : (Integer, None), 'fieldH54': (Boolean, ''),
          'fieldH55': (Boolean, '', {'depend_field' : ('fieldH56','fieldH57')}),
          'fieldH56' : (Integer, None),
          'fieldH57' : (Integer, None), 'fieldH58': (Boolean, ''),
          'fieldH59': (Boolean, ''), 'fieldH60': (Boolean, ''),
          'fieldH61': (Boolean, ''), 'fieldH62': (Boolean, ''),
          'fieldH63': (Boolean, '', {'depend_field' : ('fieldH74',)}),
          'fieldH74' : (Unicode, None),
          #
          'fieldH64' : (Integer, None),
          'fieldH65Y' : (Integer, None), 'fieldH65Z' : (Integer, None),
          'fieldH66Y' : (Integer, None), 'fieldH66Z' : (Integer, None),
          'fieldH67Y' : (Integer, None), 'fieldH67Z' : (Integer, None),
          'fieldH68Y' : (Integer, None), 'fieldH68Z' : (Integer, None),
          'fieldH69Y' : (Integer, None,{'sum': ('fieldH65Y', 'fieldH66Y','fieldH67Y', 'fieldH68Y',)}),
          'fieldH69Z' : (Integer, None,{'sum': ('fieldH65Z', 'fieldH66Z','fieldH67Z', 'fieldH68Z',)}),
          'fieldH70' : (Boolean, '', {'depend_field' : ('fieldH71',)}),
          'fieldH71' : (Integer, None),
          'fieldH72' : (Boolean, '', {'depend_field' : ('fieldH73',)}),
          'fieldH73' : (Integer, None),
          #
          'fieldI11' : (Boolean, '', {'depend_field' : ('fieldI12', 'fieldI13',
                                                           'fieldI14', 'fieldI15',
                                                           'fieldI16', 'fieldI17',
                                                           'fieldI18', 'fieldI19','fieldI29',
                                                           'fieldI20')}),
          'fieldI12' : (Integer, None), 'fieldI13' : (Integer, None),
          'fieldI14' : (Integer, None), 'fieldI15' : (Integer, None),
          'fieldI16' : (Integer, None), 'fieldI17' : (Integer, None),
          'fieldI18' : (Integer, None), 'fieldI19' : (Integer, None),
          'fieldI20' : (Integer, None), 'fieldI29' : (Integer, None),
          #
          'fieldI21' : (Boolean, '', {'depend_field' : ('fieldI22', 'fieldI23',
                                                           'fieldI24', 'fieldI25',
                                                           'fieldI26', 'fieldI27',
                                                           'fieldI28',) }),
          'fieldI22' : (Integer, None), 'fieldI23' : (Integer, None),
          'fieldI24' : (Integer, None), 'fieldI25' : (Integer, None),
          'fieldI26' : (Integer, None), 'fieldI27' : (Integer, None),
          'fieldI28' : (Integer, None),
          #
          'fieldI31' : (Integer, None),
          'fieldI32Z' : (Integer, None),
          'fieldI33Z' : (Integer, None),
          #'fieldI34Y' : (Integer, None),
          'fieldI34Z' : (Integer, None,
                         {'sum': ('fieldI32Z', 'fieldI33Z')}),


          ## comments form
          'fieldL20': (Unicode, ''),}


##############################################################################
# Alerts
##############################################################################

alertes_txt = """
A11 / C43X  = salaire moyen
E83X / E13X = prix moyen d'un livre
E86X / E16X  = prix moyen d'un phonogramme
E89X / E19X = prix moyen d'un vidéogramme
E92X / E22X = prix moyen d'un cédérom
E96X -10% <= A12 <= E96X + 10%
H11 si réponse =oui,  signaler si le champ 5 (site WEB) est non rempli
Si F17W = 0, signaler si F69X est différent de 0

A11 / C43X        = salaire moyen
F46X / F18X*100   = % desserte

E85X / E13X       = prix moyen d'un livre
E88X / E16X        = prix moyen d'un phonogramme
E91X / E19X        = prix moyen d'un vidéogramme
E94X / E22X       = prix moyen d'un cédérom
E98X -10% <= A12 <= E98X + 10%

H11 si réponse =oui,  signaler si le champ 5 (site WEB) est non rempli
Si F17W = 0, signaler si F69X est différent de 0
"""

alertes = [
('C', u"E85X / E13X = prix moyen d'un livre         " ,"E85X / E13X    " ),
('D', u"E88X / E16X  = prix moyen d'un phonogramme  " ,"E88X / E16X    " ),
('E', u"E91X / E19X = prix moyen d'un vidéogramme   " ,"E91X / E19X    " ),
('F', u"E94X / E22X = prix moyen d'un cédérom       " ,"E94X / E22X    " ),
('G', u"E98X - 10% <= A12 <= E98X +10 % : variation  +/- 10 % des dépenses documentaires",
                 'int(E98X) * 0.9 < A12 < int(E98X) * 1.1' )
]


##############################################################################
# Controls
##############################################################################

controles = sum2controle(schema=schema)


##############################################################################
# Check that all keys are in schema
##############################################################################

def checkBDP():
    checkBib(bib_type='BDP', max=30, schema=schema)

if __name__ == '__main__':
    checkBDP()

