# -*- coding: ISO-8859-1 -*-

# Import from python
from pprint import pprint
import re, sets

# Import from itools
from itools.handlers import IO

# Import from Culture 
from CultureTypes import Checkboxes, Integer
from schema import sum2controle, checkBib


schema = {'field1': (IO.Unicode, ''), 'field2': (IO.Unicode, ''),
          'field3': (IO.Unicode, ''), 'field4': (IO.Unicode, ''),
          'field5': (IO.Unicode, ''), 'field6': (IO.Unicode, ''),
          'field7': (IO.Unicode, ''), 'field8': (IO.Unicode, ''),
          'field9': (IO.Unicode, ''), 'field10': (IO.Unicode, ''),
          'field11': (IO.Unicode, ''),'field12': (IO.Unicode, ''),
          #
          'fieldA11': (Integer, None), 'fieldA12': (Integer, None),
          'fieldA13': (Integer, None), 'fieldA14': (Integer, None),
          'fieldA15': (Integer, None), 'fieldA16': (Integer, None),
          'fieldA17': (Integer, None, 
                       {'sum': ('fieldA11', 'fieldA12', 'fieldA13', 
                                'fieldA14', 'fieldA15', 'fieldA16')}),
          #
          'fieldA21': (Integer, None), 'fieldA22': (Integer, None),
          'fieldA23': (Integer, None), 'fieldA24': (Integer, None),
          #
          'fieldA31': (Integer, None, {'depend_field' : ('fieldB32',)}),
          'fieldA32': (Integer, None),
          #
          'fieldB11X': (Integer, None), 'fieldB11Y': (Integer, None),
          'fieldB11Z': (Integer, None), 'fieldB12X': (Integer, None),

          'fieldB12Y': (Integer, None), 'fieldB12Z': (Integer, None),
          'fieldB13X': (Integer, None), 'fieldB13Y': (Integer, None),
          'fieldB13Z': (Integer, None), 'fieldB14Z': (Integer, None),
          #
          'fieldB21': (Integer, None), 'fieldB22': (Integer, None),
          'fieldB23': (Integer, None),
          #
          'fieldB31': (IO.Boolean, '', {'depend_field' : ('fieldB32',)} ),
          'fieldB32': (IO.Unicode, ''),
          'fieldB33': (IO.Boolean, '', {'depend_field' : ('fieldB34','fieldB35')}),
          'fieldB34': (Integer, None),
          'fieldB35': (IO.Unicode, ''), 'fieldB36X': (Integer, None),
          'fieldB36Y': (Integer, None), 'fieldB37X': (Integer, None),
          'fieldB37Y': (Integer, None), 'fieldB38X': (Integer, None),
          'fieldB38Y': (Integer, None), 'fieldB39': (IO.Boolean, None),
          #
          'fieldB40': (IO.Boolean, None),
          #
          'fieldC11S' : (Integer, None), 'fieldC11T' : (IO.Unicode, None),
          'fieldC11U' : (Integer, None), 'fieldC11V' : (IO.Boolean, None),
          'fieldCV': (Checkboxes, ''),
          'fieldC11W' : (Integer, None), 'fieldC11X' : (IO.Unicode, None),
          'fieldC11Y' : (Integer, None), 'fieldC11Z' : (Integer, None),
          #
          'fieldC12S' : (Integer, None), 'fieldC12T' : (IO.Unicode, None),
          'fieldC12U' : (Integer, None), 'fieldC12V' : (IO.Boolean, None),
          'fieldC12W' : (Integer, None), 'fieldC12X' : (IO.Unicode, None),
          'fieldC12Y' : (Integer, None), 'fieldC12Z' : (Integer, None),
          #
          'fieldC13S' : (Integer, None), 'fieldC13T' : (IO.Unicode, None),
          'fieldC13U' : (Integer, None), 'fieldC13V' : (IO.Boolean, None),
          'fieldC13W' : (Integer, None), 'fieldC13X' : (IO.Unicode, None),
          'fieldC13Y' : (Integer, None), 'fieldC13Z' : (Integer, None),
          #
          'fieldC14S' : (Integer, None), 'fieldC14T' : (IO.Unicode, None),
          'fieldC14U' : (Integer, None), 'fieldC14V' : (IO.Boolean, None),
          'fieldC14W' : (Integer, None), 'fieldC14X' : (IO.Unicode, None),
          'fieldC14Y' : (Integer, None), 'fieldC14Z' : (Integer, None),
          #
          'fieldC15S' : (Integer, None), 'fieldC15T' : (IO.Unicode, None),
          'fieldC15U' : (Integer, None), 'fieldC15V' : (IO.Boolean, None),
          'fieldC15W' : (Integer, None), 'fieldC15X' : (IO.Unicode, None),
          'fieldC15Y' : (Integer, None), 'fieldC15Z' : (Integer, None),
          #
          'fieldC16S' : (Integer, None), 'fieldC16T' : (IO.Unicode, None),
          'fieldC16U' : (Integer, None), 'fieldC16V' : (IO.Boolean, None),
          'fieldC16W' : (Integer, None), 'fieldC16X' : (IO.Unicode, None),
          'fieldC16Y' : (Integer, None), 'fieldC16Z' : (Integer, None),
          #
          'fieldC21S' : (Integer, None), 'fieldC21T' : (IO.Unicode, None),
          'fieldC21U' : (Integer, None), 'fieldC21V' : (IO.Boolean, None),
          'fieldC21W' : (Integer, None), 'fieldC21X' : (IO.Unicode, None),
          'fieldC21Y' : (Integer, None), 'fieldC21Z' : (Integer, None),
          #
          'fieldC22S' : (Integer, None), 'fieldC22T' : (IO.Unicode, None),
          'fieldC22U' : (Integer, None), 'fieldC22V' : (IO.Boolean, None),
          'fieldC22W' : (Integer, None), 'fieldC22X' : (IO.Unicode, None),
          'fieldC22Y' : (Integer, None), 'fieldC22Z' : (Integer, None),
          #
          'fieldC23S' : (Integer, None), 'fieldC23T' : (IO.Unicode, None),
          'fieldC23U' : (Integer, None), 'fieldC23V' : (IO.Boolean, None),
          'fieldC23W' : (Integer, None), 'fieldC23X' : (IO.Unicode, None),
          'fieldC23Y' : (Integer, None), 'fieldC23Z' : (Integer, None),
          #
          'fieldC31S' : (Integer, None), 'fieldC31T' : (IO.Unicode, None),
          'fieldC31U' : (Integer, None), 'fieldC31V' : (IO.Boolean, None),
          'fieldC31W' : (Integer, None), 'fieldC31X' : (IO.Unicode, None),
          'fieldC31Y' : (Integer, None), 'fieldC31Z' : (Integer, None),
          #
          'fieldC32S' : (Integer, None), 'fieldC32T' : (IO.Unicode, None),
          'fieldC32U' : (Integer, None), 'fieldC32V' : (IO.Boolean, None),
          'fieldC32W' : (Integer, None), 'fieldC32X' : (IO.Unicode, None),
          'fieldC32Y' : (Integer, None), 'fieldC32Z' : (Integer, None),
          #
          'fieldC33S' : (Integer, None), 'fieldC33T' : (IO.Unicode, None),
          'fieldC33U' : (Integer, None), 'fieldC33V' : (IO.Boolean, None),
          'fieldC33W' : (Integer, None), 'fieldC33X' : (IO.Unicode, None),
          'fieldC33Y' : (Integer, None), 'fieldC33Z' : (Integer, None),
          #
          'fieldC34S' : (Integer, None), 'fieldC34T' : (IO.Unicode, None),
          'fieldC34U' : (Integer, None), 'fieldC34V' : (IO.Boolean, None),
          'fieldC34W' : (Integer, None), 'fieldC34X' : (IO.Unicode, None),
          'fieldC34Y' : (Integer, None), 'fieldC34Z' : (Integer, None),
          #
          'fieldC41S' : (Integer, None), 
          'fieldC41U' : (Integer, None), 'fieldC41V' : (IO.Boolean, None),
          'fieldC41W' : (Integer, None), 
          'fieldC41Y' : (Integer, None), 'fieldC41Z' : (Integer, None),
          #
          'fieldC42S' : (Integer, None), 
          'fieldC42V' : (IO.Boolean, None),
          'fieldC42W' : (Integer, None), 
          'fieldC42Z' : (Integer, None),
          #
          'fieldC43S' : (Integer, None), 'fieldC43T' : (IO.Unicode, None),
          'fieldC43U' : (Integer, None), 
          'fieldC43W' : (Integer, None), 'fieldC43X' : (IO.Unicode, None),
          'fieldC43Y' : (Integer, None), 'fieldC43Z' : (Integer, None),
          #
          'fieldC51Z' : (Integer, None),
          #
          'fieldD11X' : (Integer, None), 'fieldD11Y' : (Integer, None),
          'fieldD11Z' : (Integer, None),
          'fieldD12X' : (Integer, None), 'fieldD12Y' : (Integer, None),
          'fieldD12Z' : (Integer, None),
          'fieldD13X' : (Integer, None), 'fieldD13Y' : (Integer, None),
          'fieldD13Z' : (Integer, None), 
          'fieldD14X' : (Integer, None), 'fieldD14Y' : (Integer, None),
          'fieldD14Z' : (Integer, None),
          'fieldD15X' : (Integer, None), 'fieldD15Y' : (Integer, None),
          'fieldD15Z' : (Integer, None),
          'fieldD16X' : (Integer, None), 'fieldD16Y' : (Integer, None),
          'fieldD16Z' : (Integer, None),
          'fieldD17X' : (Integer, None), 'fieldD17Y' : (Integer, None),
          'fieldD17Z' : (Integer, None),
          'fieldD18X' : (Integer, None), 'fieldD18Y' : (Integer, None),
          'fieldD18Z' : (Integer, None),
          'fieldD19X' : (Integer, None), 'fieldD19Y' : (Integer, None),
          'fieldD19Z' : (Integer, None), 
          'fieldD20X' : (Integer, None), 'fieldD20Y' : (Integer, None),
          'fieldD20Z' : (Integer, None),
          'fieldD21X' : (Integer, None), 'fieldD21Y' : (Integer, None),
          'fieldD21Z' : (Integer, None),
          'fieldD22X' : (Integer, None), 'fieldD22Y' : (Integer, None),
          'fieldD22Z' : (Integer, None),
          'fieldD23X' : (Integer, None), 'fieldD23Y' : (Integer, None),
          'fieldD23Z' : (Integer, None),
          'fieldD24X' : (Integer, None), 'fieldD24Y' : (Integer, None),
          'fieldD24Z' : (Integer, None), 'fieldD31' : (Integer, None),
          #
          'fieldD32' : (Integer, None),
          #
          'fieldE11X' : (Integer, None), 'fieldE11Y' : (Integer, None),
          'fieldE11Z' : (Integer, None), 
          'fieldE12X' : (Integer, None), 'fieldE12Y' : (Integer, None),
          'fieldE12Z' : (Integer, None),
          'fieldE13X' : (Integer, None), 'fieldE13Y' : (Integer, None),
          'fieldE13Z' : (Integer, None),
          'fieldE14X' : (Integer, None), 'fieldE14Y' : (Integer, None),
          'fieldE14Z' : (Integer, None),
          'fieldE15X' : (Integer, None), 'fieldE15Y' : (Integer, None),
          'fieldE15Z' : (Integer, None),
          'fieldE16X' : (Integer, None), 'fieldE16Y' : (Integer, None),
          'fieldE16Z' : (Integer, None),
          'fieldE17X' : (Integer, None), 'fieldE17Y' : (Integer, None),
          'fieldE17Z' : (Integer, None),
          'fieldE18X' : (Integer, None), 'fieldE18Y' : (Integer, None),
          'fieldE18Z' : (Integer, None),
          'fieldE19X' : (Integer, None), 'fieldE19Y' : (Integer, None),
          'fieldE19Z' : (Integer, None),
          'fieldE20X' : (Integer, None), 'fieldE20Y' : (Integer, None),
          'fieldE20Z' : (Integer, None),
          'fieldE21X' : (Integer, None), 'fieldE21Y' : (Integer, None),
          'fieldE21Z' : (Integer, None), 
          'fieldE22X' : (Integer, None), 'fieldE22Y' : (Integer, None),
          'fieldE22Z' : (Integer, None),
          'fieldE23X' : (Integer, None), 'fieldE23Y' : (Integer, None),
          'fieldE23Z' : (Integer, None),
          #
          'fieldE31X' : (Integer, None), 'fieldE31Y' : (Integer, None),
          'fieldE31Z' : (Integer, None),
          'fieldE32X' : (Integer, None), 'fieldE32Y' : (Integer, None),
          'fieldE32Z' : (Integer, None),
          'fieldE33X' : (Integer, None), 'fieldE33Y' : (Integer, None),
          'fieldE33Z' : (Integer, None),
          'fieldE34X' : (Integer, None), 'fieldE34Y' : (Integer, None),
          'fieldE34Z' : (Integer, None),
          'fieldE35X' : (Integer, None), 'fieldE35Y' : (Integer, None),
          'fieldE35Z' : (Integer, None),
          'fieldE36X' : (Integer, None), 'fieldE36Y' : (Integer, None),
          'fieldE36Z' : (Integer, None),
          'fieldE37X' : (Integer, None), 'fieldE37Y' : (Integer, None),
          'fieldE37Z' : (Integer, None),
          'fieldE38X' : (Integer, None), 'fieldE38Y' : (Integer, None),
          'fieldE38Z' : (Integer, None), 
          'fieldE39X' : (Integer, None), 'fieldE39Y' : (Integer, None),
          'fieldE39Z' : (Integer, None),
          'fieldE40X' : (Integer, None), 'fieldE40Y' : (Integer, None),
          'fieldE40Z' : (Integer, None),
          'fieldE41X' : (Integer, None), 'fieldE41Y' : (Integer, None),
          'fieldE41Z' : (Integer, None),
          'fieldE42X' : (Integer, None), 'fieldE42Y' : (Integer, None),
          'fieldE42Z' : (Integer, None),
          'fieldE43X' : (Integer, None), 'fieldE43Y' : (Integer, None),
          'fieldE43Z' : (Integer, None),
          #
          'fieldE51X' : (Integer, None), 'fieldE51Y' : (Integer, None),
          'fieldE51Z' : (Integer, None),
          'fieldE52X' : (Integer, None), 'fieldE52Y' : (Integer, None),
          'fieldE52Z' : (Integer, None),
          'fieldE53X' : (Integer, None), 'fieldE53Y' : (Integer, None),
          'fieldE53Z' : (Integer, None),
          'fieldE54X' : (Integer, None), 'fieldE54Y' : (Integer, None),
          'fieldE54Z' : (Integer, None),
          'fieldE55X' : (Integer, None), 'fieldE55Y' : (Integer, None),
          'fieldE55Z' : (Integer, None), 
          'fieldE56X' : (Integer, None), 'fieldE56Y' : (Integer, None),
          'fieldE56Z' : (Integer, None),
          'fieldE57X' : (Integer, None), 'fieldE57Y' : (Integer, None),
          'fieldE57Z' : (Integer, None),
          'fieldE58X' : (Integer, None), 'fieldE58Y' : (Integer, None),
          'fieldE58Z' : (Integer, None),
          'fieldE59X' : (Integer, None), 'fieldE59Y' : (Integer, None),
          'fieldE59Z' : (Integer, None),
          'fieldE60X' : (Integer, None), 'fieldE60Y' : (Integer, None),
          'fieldE60Z' : (Integer, None),
          'fieldE61X' : (Integer, None), 'fieldE61Y' : (Integer, None),
          'fieldE61Z' : (Integer, None),
          'fieldE62X' : (Integer, None), 'fieldE62Y' : (Integer, None),
          'fieldE62Z' : (Integer, None),
          'fieldE63X' : (Integer, None), 'fieldE63Y' : (Integer, None),
          'fieldE63Z' : (Integer, None),
          #
          'fieldE71X' : (Integer, None), 'fieldE71Y' : (Integer, None),
          'fieldE71Z' : (Integer, None),
          'fieldE72X' : (Integer, None), 'fieldE72Y' : (Integer, None),
          'fieldE72Z' : (Integer, None), 
          'fieldE73X' : (Integer, None), 'fieldE73Y' : (Integer, None),
          'fieldE73Z' : (Integer, None),
          #
          'fieldE81X' : (Integer, None), 'fieldE81Y' : (Integer, None),
          'fieldE81Z' : (Integer, None),
          'fieldE82X' : (Integer, None), 'fieldE82Y' : (Integer, None),
          'fieldE82Z' : (Integer, None),
          #
          'fieldE83X' : (Integer, None), 'fieldE83Y' : (Integer, None),
          'fieldE83Z' : (Integer, None),
          'fieldE84X' : (Integer, None), 'fieldE84Y' : (Integer, None),
          'fieldE84Z' : (Integer, None),
          'fieldE85X' : (Integer, None), 'fieldE85Y' : (Integer, None),
          'fieldE85Z' : (Integer, None),
          'fieldE86X' : (Integer, None), 'fieldE86Y' : (Integer, None),
          'fieldE86Z' : (Integer, None),
          'fieldE87X' : (Integer, None), 'fieldE87Y' : (Integer, None),
          'fieldE87Z' : (Integer, None),
          'fieldE88X' : (Integer, None), 'fieldE88Y' : (Integer, None),
          'fieldE88Z' : (Integer, None),
          'fieldE89X' : (Integer, None), 'fieldE89Y' : (Integer, None),
          'fieldE89Z' : (Integer, None), 
          'fieldE90X' : (Integer, None), 'fieldE90Y' : (Integer, None),
          'fieldE90Z' : (Integer, None),
          'fieldE91X' : (Integer, None), 'fieldE91Y' : (Integer, None),
          'fieldE91Z' : (Integer, None),
          'fieldE92X' : (Integer, None), 'fieldE92Y' : (Integer, None),
          'fieldE92Z' : (Integer, None),
          'fieldE93X' : (Integer, None), 'fieldE93Y' : (Integer, None),
          'fieldE93Z' : (Integer, None),
          'fieldE94X' : (Integer, None), 'fieldE94Y' : (Integer, None),
          'fieldE94Z' : (Integer, None),
          'fieldE95X' : (Integer, None), 'fieldE95Y' : (Integer, None),
          'fieldE95Z' : (Integer, None),
          'fieldE96X' : (Integer, None), 'fieldE96Y' : (Integer, None),
          'fieldE96Z' : (Integer, None),
          'fieldE97X' : (Integer, None), 'fieldE97Y' : (Integer, None),
          'fieldE97Z' : (Integer, None),
          'fieldE98X' : (Integer, None), 'fieldE98Y' : (Integer, None),
          'fieldE98Z' : (Integer, None),
          #
          'fieldF11W' : (Integer, None), 'fieldF11X' : (Integer, None),
          'fieldF11Y' : (Integer, None),
          'fieldF12W' : (Integer, None), 'fieldF12X' : (Integer, None),
          'fieldF12Y' : (Integer, None),
          'fieldF13W' : (Integer, None), 'fieldF13X' : (Integer, None),
          'fieldF13Y' : (Integer, None),
          'fieldF14W' : (Integer, None), 'fieldF14X' : (Integer, None),
          'fieldF14Y' : (Integer, None),
          'fieldF15W' : (Integer, None), 'fieldF15X' : (Integer, None),
          'fieldF15Y' : (Integer, None),
          'fieldF16W' : (Integer, None), 'fieldF16X' : (Integer, None),
          'fieldF16Y' : (Integer, None),
          'fieldF17W' : (Integer, None), 'fieldF17X' : (Integer, None),
          'fieldF17Y' : (Integer, None),
          'fieldF18W' : (Integer, None), 'fieldF18X' : (Integer, None),
          'fieldF18Y' : (Integer, None),
          'fieldF19X' : (Integer, None), 'fieldF19Y' : (Integer, None),
          'fieldF20X' : (Integer, None), 'fieldF20Y' : (Integer, None),
          'fieldF21X' : (Integer, None), 'fieldF21Y' : (Integer, None),
          #
          'fieldF31Y' : (Integer, None), 'fieldF31Z' : (Integer, None),
          'fieldF32Y' : (Integer, None), 'fieldF32Z' : (Integer, None),
          'fieldF33Y' : (Integer, None), 'fieldF33Z' : (Integer, None),
          'fieldF34Y' : (Integer, None), 'fieldF34Z' : (Integer, None),
          'fieldF35Y' : (Integer, None), 'fieldF35Z' : (Integer, None),
          'fieldF36Y' : (Integer, None), 'fieldF36Z' : (Integer, None),
          'fieldF37Y' : (Integer, None), 'fieldF37Z' : (Integer, None),
          'fieldF38Y' : (Integer, None), 'fieldF38Z' : (Integer, None),
          #
          'fieldF41W' : (Integer, None), 'fieldF41X' : (Integer, None),
          'fieldF41Y' : (Integer, None),
          'fieldF42W' : (Integer, None), 'fieldF42X' : (Integer, None),
          'fieldF42Y' : (Integer, None),
          'fieldF43W' : (Integer, None), 'fieldF43X' : (Integer, None),
          'fieldF43Y' : (Integer, None),
          'fieldF44W' : (Integer, None), 'fieldF44X' : (Integer, None),
          'fieldF44Y' : (Integer, None),
          'fieldF45W' : (Integer, None), 'fieldF45X' : (Integer, None),
          'fieldF45Y' : (Integer, None),
          'fieldF46W' : (Integer, None), 'fieldF46X' : (Integer, None),
          'fieldF46Y' : (Integer, None),
          #
          'fieldF51W' : (Integer, None), 'fieldF51X' : (Integer, None),
          'fieldF51Y' : (Integer, None), 'fieldF51Z' : (Integer, None),
          'fieldF52W' : (Integer, None), 'fieldF52X' : (Integer, None),
          'fieldF52Y' : (Integer, None), 'fieldF52Z' : (Integer, None),
          'fieldF53W' : (Integer, None), 'fieldF53X' : (Integer, None),
          'fieldF53Y' : (Integer, None), 'fieldF53Z' : (Integer, None),
          'fieldF54W' : (Integer, None), 'fieldF54X' : (Integer, None),
          'fieldF54Y' : (Integer, None), 'fieldF54Z' : (Integer, None),
          'fieldF55W' : (Integer, None), 'fieldF55X' : (Integer, None),
          'fieldF55Y' : (Integer, None), 'fieldF55Z' : (Integer, None),
          'fieldF56W' : (Integer, None), 'fieldF56X' : (Integer, None),
          'fieldF56Y' : (Integer, None), 'fieldF56Z' : (Integer, None),
          #
          'fieldF61W' : (Integer, None), 'fieldF61X' : (Integer, None),
          'fieldF61Y' : (Integer, None), 'fieldF61Z' : (Integer, None),
          'fieldF62W' : (Integer, None), 'fieldF62X' : (Integer, None),
          'fieldF62Y' : (Integer, None), 'fieldF62Z' : (Integer, None),
          'fieldF63W' : (Integer, None), 'fieldF63X' : (Integer, None),
          'fieldF63Y' : (Integer, None), 'fieldF63Z' : (Integer, None),
          'fieldF64W' : (Integer, None), 'fieldF64X' : (Integer, None),
          'fieldF64Y' : (Integer, None), 'fieldF64Z' : (Integer, None),
          'fieldF65W' : (Integer, None), 'fieldF65X' : (Integer, None),
          'fieldF65Y' : (Integer, None), 'fieldF65Z' : (Integer, None),
          'fieldF66W' : (Integer, None), 'fieldF66X' : (Integer, None),
          'fieldF66Y' : (Integer, None), 'fieldF66Z' : (Integer, None),
          'fieldF67W' : (Integer, None), 'fieldF67X' : (Integer, None),
          'fieldF67Y' : (Integer, None), 'fieldF67Z' : (Integer, None),
          'fieldF68W' : (Integer, None), 'fieldF68X' : (Integer, None),
          'fieldF68Y' : (Integer, None), 'fieldF68Z' : (Integer, None),
          'fieldF69W' : (Integer, None), 'fieldF69X' : (Integer, None),
          'fieldF69Y' : (Integer, None), 'fieldF69Z' : (Integer, None),
          #
          'fieldG11V' : (Integer, None), 'fieldG11W' : (Integer, None),
          'fieldG11X' : (Integer, None), 'fieldG11Y' : (Integer, None),
          'fieldG11Z' : (Integer, None),
          'fieldG12V' : (Integer, None), 'fieldG12W' : (Integer, None),
          'fieldG12X' : (Integer, None), 'fieldG12Y' : (Integer, None),
          'fieldG12Z' : (Integer, None),
          'fieldG13V' : (Integer, None), 'fieldG13W' : (Integer, None),
          'fieldG13X' : (Integer, None), 'fieldG13Y' : (Integer, None),
          'fieldG13Z' : (Integer, None),
          'fieldG14V' : (Integer, None), 'fieldG14W' : (Integer, None),
          'fieldG14X' : (Integer, None), 'fieldG14Y' : (Integer, None),
          'fieldG14Z' : (Integer, None),
          'fieldG15V' : (Integer, None), 'fieldG15W' : (Integer, None),
          'fieldG15X' : (Integer, None), 'fieldG15Y' : (Integer, None),
          'fieldG15Z' : (Integer, None),
          'fieldG16V' : (Integer, None), 'fieldG16W' : (Integer, None),
          'fieldG16X' : (Integer, None), 'fieldG16Y' : (Integer, None),
          'fieldG16Z' : (Integer, None),
          'fieldG17V' : (Integer, None), 'fieldG17W' : (Integer, None),
          'fieldG17X' : (Integer, None), 'fieldG17Y' : (Integer, None),
          'fieldG17Z' : (Integer, None),
          'fieldG18V' : (Integer, None), 'fieldG18W' : (Integer, None),
          'fieldG18X' : (Integer, None), 'fieldG18Y' : (Integer, None),
          'fieldG18Z' : (Integer, None),
          'fieldG19V' : (Integer, None), 'fieldG19W' : (Integer, None),
          'fieldG19X' : (Integer, None), 'fieldG19Y' : (Integer, None),
          'fieldG19Z' : (Integer, None),
          'fieldG20V' : (Integer, None), 'fieldG20W' : (Integer, None),
          'fieldG20X' : (Integer, None), 'fieldG20Y' : (Integer, None),
          'fieldG20Z' : (Integer, None),
          'fieldG21V' : (Integer, None), 'fieldG21W' : (Integer, None),
          'fieldG21X' : (Integer, None), 'fieldG21Y' : (Integer, None),
          'fieldG21Z' : (Integer, None),
          'fieldG22V' : (Integer, None), 'fieldG22W' : (Integer, None),
          'fieldG22X' : (Integer, None), 'fieldG22Y' : (Integer, None),
          'fieldG22Z' : (Integer, None),
          #
          'fieldG31X' : (Integer, None), 'fieldG31Y' : (Integer, None),
          'fieldG31Z' : (Integer, None),
          'fieldG32X' : (Integer, None), 'fieldG32Y' : (Integer, None),
          'fieldG32Z' : (Integer, None),
          'fieldG33X' : (Integer, None), 'fieldG33Y' : (Integer, None),
          'fieldG33Z' : (Integer, None),
          'fieldG34X' : (Integer, None), 'fieldG34Y' : (Integer, None),
          'fieldG34Z' : (Integer, None),
          'fieldG35X' : (Integer, None), 'fieldG35Y' : (Integer, None),
          'fieldG35Z' : (Integer, None),
          'fieldG36X' : (Integer, None), 'fieldG36Y' : (Integer, None),
          'fieldG36Z' : (Integer, None),
          'fieldG37X' : (Integer, None), 'fieldG37Y' : (Integer, None),
          'fieldG37Z' : (Integer, None),
          'fieldG38X' : (Integer, None), 'fieldG38Y' : (Integer, None),
          'fieldG38Z' : (Integer, None),
          'fieldG39X' : (Integer, None), 'fieldG39Y' : (Integer, None),
          'fieldG39Z' : (Integer, None),
          'fieldG40X' : (Integer, None), 'fieldG40Y' : (Integer, None),
          'fieldG40Z' : (Integer, None),
          'fieldG41X' : (Integer, None), 'fieldG41Y' : (Integer, None),
          'fieldG41Z' : (Integer, None),
          'fieldG42X' : (Integer, None), 'fieldG42Y' : (Integer, None),
          'fieldG42Z' : (Integer, None),
          #
          'fieldH11': (IO.Boolean, '', {'depend_field' : ('fieldH12',
                                                          'fieldH13', 
                                                          'fieldH14',
                                                          'fieldH15', 
                                                          'fieldH16',
                                                          'fieldH17', 
                                                          'fieldH18')}),
          'fieldH12': (IO.Boolean, ''),
          'fieldH13': (IO.Boolean, ''), 'fieldH14': (IO.Boolean, ''),
          'fieldH15': (IO.Boolean, ''), 'fieldH16': (IO.Boolean, ''),
          'fieldH17' : (Integer, None), 'fieldH18' : (Integer, None),
          #
          'fieldH21': (IO.Boolean, '', {'depend_field' : ('fieldH22',)}),
          'fieldH22': (IO.Unicode, None),
          'fieldH23': (IO.Boolean, '', {'depend_field' : ('fieldH24',)}),
          'fieldH24': (IO.Unicode, None),
          'fieldH25': (IO.Boolean, '', {'depend_field' : ('fieldH26',)}),
          'fieldH26': (IO.Unicode, None),
          'fieldH27': (IO.Boolean, '', {'depend_field' : ('fieldH28',
                                                              'fieldH29')}),
          'fieldH28': (IO.Boolean, ''),
          'fieldH29': (IO.Boolean, ''),
          #
          'fieldH31V' : (IO.Boolean, '', {'depend_field' : ('fieldH31W','fieldH31X','fieldH31Y','fieldH31Z')}), 
          'fieldH31W' : (Integer, None),
          'fieldH31X' : (Integer, None), 'fieldH31Y' : (Integer, None),
          'fieldH31Z' : (Integer, None),
          'fieldH32V' : (IO.Boolean, '', {'depend_field' : ('fieldH32W','fieldH32X','fieldH32Y','fieldH32Z')}),
          'fieldH32W' : (Integer, None),
          'fieldH32X' : (Integer, None), 'fieldH32Y' : (Integer, None),
          'fieldH32Z' : (Integer, None),
          'fieldH33V' : (IO.Boolean, '', {'depend_field' : ('fieldH33W','fieldH33X','fieldH33Y','fieldH33Z')}),
          'fieldH33W' : (Integer, None),
          'fieldH33X' : (Integer, None), 'fieldH33Y' : (Integer, None),
          'fieldH33Z' : (Integer, None),
          'fieldH34V' : (IO.Boolean, '', {'depend_field' : ('fieldH34W','fieldH34X','fieldH34Y','fieldH34Z')}),
          'fieldH34W' : (Integer, None),
          'fieldH34X' : (Integer, None), 'fieldH34Y' : (Integer, None),
          'fieldH34Z' : (Integer, None),
          'fieldH35V' : (IO.Boolean, '', {'depend_field' : ('fieldH35W','fieldH35X','fieldH35Y','fieldH35Z')}),
          'fieldH35W' : (Integer, None),
          'fieldH35X' : (Integer, None), 'fieldH35Y' : (Integer, None),
          'fieldH35Z' : (Integer, None),
          'fieldH36V' : (IO.Boolean, '', {'depend_field' : ('fieldH36W','fieldH36X','fieldH36Y','fieldH36Z')}), 
          'fieldH36W' : (Integer, None),
          'fieldH36X' : (Integer, None), 'fieldH36Y' : (Integer, None),
          'fieldH36Z' : (Integer, None),
          'fieldH37V' : (IO.Boolean, '', {'depend_field' : ('fieldH37W','fieldH37X','fieldH37Y','fieldH37Z')}), 
          'fieldH37W' : (Integer, None),
          'fieldH37X' : (Integer, None), 'fieldH37Y' : (Integer, None),
          'fieldH37Z' : (Integer, None),
          'fieldH38V' : (IO.Boolean, '', {'depend_field' : ('fieldH38W','fieldH38X','fieldH38Y','fieldH38Z')}), 
          'fieldH38W' : (Integer, None),
          'fieldH38X' : (Integer, None), 'fieldH38Y' : (Integer, None),
          'fieldH38Z' : (Integer, None),
          'fieldH39V' : (IO.Boolean, '', {'depend_field' : ('fieldH39W','fieldH39X','fieldH39Y','fieldH39Z')}), 
          'fieldH39W' : (Integer, None),
          'fieldH39X' : (Integer, None), 'fieldH39Y' : (Integer, None),
          'fieldH39Z' : (Integer, None),
          #
          'fieldH41X' : (IO.Boolean, '', {'depend_field' : ('fieldH41Y','fieldH41Z')}), 'fieldH41Y' : (Integer, None),
          'fieldH41Z' : (Integer, None),
          'fieldH42X' : (IO.Boolean, '', {'depend_field' : ('fieldH42Y','fieldH42Z')}), 'fieldH42Y' : (Integer, None),
          'fieldH42Z' : (Integer, None),
          'fieldH43X' : (IO.Boolean, '', {'depend_field' : ('fieldH43Y','fieldH43Z')}), 'fieldH43Y' : (Integer, None),
          'fieldH43Z' : (Integer, None),
          'fieldH44X' : (IO.Boolean, '', {'depend_field' : ('fieldH44Y','fieldH44Z')}), 'fieldH44Y' : (Integer, None),
          'fieldH44Z' : (Integer, None),
          'fieldH45X' : (IO.Boolean, '', {'depend_field' : ('fieldH45Y','fieldH45Z')}), 'fieldH45Y' : (Integer, None),
          'fieldH45Z' : (Integer, None),
          'fieldH46X' : (IO.Boolean, '', {'depend_field' : ('fieldH46Y','fieldH46Z')}), 'fieldH46Y' : (Integer, None),
          'fieldH46Z' : (Integer, None),
          'fieldH47X' : (IO.Boolean, '', {'depend_field' : ('fieldH47Y','fieldH47Z')}), 'fieldH47Y' : (Integer, None),
          'fieldH47Z' : (Integer, None),
          'fieldH48X' : (IO.Boolean, '', {'depend_field' : ('fieldH48Y','fieldH48Z')}), 'fieldH48Y' : (Integer, None),
          'fieldH48Z' : (Integer, None),
          'fieldH49X' : (IO.Boolean, '', {'depend_field' : ('fieldH49Y','fieldH49Z')}), 'fieldH49Y' : (Integer, None),
          'fieldH49Z' : (Integer, None),
          #
          'fieldH51':   (IO.Boolean, '', {'depend_field' : ('fieldH52','fieldH53')}),
          'fieldH52' : (Integer, None),
          'fieldH53' : (Integer, None), 'fieldH54': (IO.Boolean, ''),
          'fieldH55': (IO.Boolean, '', {'depend_field' : ('fieldH56','fieldH57')}),
          'fieldH56' : (Integer, None),
          'fieldH57' : (Integer, None), 'fieldH58': (IO.Boolean, ''),
          'fieldH59': (IO.Boolean, ''), 'fieldH60': (IO.Boolean, ''),
          'fieldH61': (IO.Boolean, ''), 'fieldH62': (IO.Boolean, ''),
          'fieldH63': (IO.Boolean, '', {'depend_field' : ('fieldH74',)}),
          'fieldH74' : (IO.Unicode, None),
          #
          'fieldH64' : (Integer, None),
          'fieldH65Y' : (Integer, None), 'fieldH65Z' : (Integer, None),
          'fieldH66Y' : (Integer, None), 'fieldH66Z' : (Integer, None),
          'fieldH67Y' : (Integer, None), 'fieldH67Z' : (Integer, None),
          'fieldH68Y' : (Integer, None), 'fieldH68Z' : (Integer, None),
          'fieldH69Y' : (Integer, None), 'fieldH69Z' : (Integer, None),
          'fieldH70' : (IO.Boolean, '', {'depend_field' : ('fieldH71',)}),
          'fieldH71' : (Integer, None),
          'fieldH72' : (IO.Boolean, '', {'depend_field' : ('fieldH73',)}),
          'fieldH73' : (Integer, None),
          #
          'fieldI11' : (IO.Boolean, '', {'depend_field' : ('fieldI12', 'fieldI13',
                                                           'fieldI14', 'fieldI15',
                                                           'fieldI16', 'fieldI17',
                                                           'fieldI18', 'fieldI19',
                                                           'fieldI20')}),
          'fieldI12' : (Integer, None), 'fieldI13' : (Integer, None),
          'fieldI14' : (Integer, None), 'fieldI15' : (Integer, None),
          'fieldI16' : (Integer, None), 'fieldI17' : (Integer, None),
          'fieldI18' : (Integer, None), 'fieldI19' : (Integer, None),
          'fieldI20' : (Integer, None),
          #
          'fieldI21' : (IO.Boolean, '', {'depend_field' : ('fieldI22', 'fieldI23',
                                                           'fieldI24', 'fieldI25',
                                                           'fieldI26', 'fieldI27',
                                                           'fieldI28',) }),
          'fieldI22' : (Integer, None), 'fieldI23' : (Integer, None),
          'fieldI24' : (Integer, None), 'fieldI25' : (Integer, None),
          'fieldI26' : (Integer, None), 'fieldI27' : (Integer, None),
          'fieldI28' : (Integer, None),
          #
          'fieldI31' : (Integer, None),
          'fieldI32Z' : (Integer, None),
          'fieldI33Z' : (Integer, None),
          'fieldI34Y' : (Integer, None), 
          'fieldI34Z' : (Integer, None, 
                         {'sum': ('fieldI32Z', 'fieldI33Z')})
          }

##############################################################################
# Alerts
##############################################################################

alertes_txt = """
A11 / C43X  = salaire moyen                 
F46X / F18X*100| = % desserte
E83X / E13X = prix moyen d'un livre
E86X / E16X  = prix moyen d'un phonogramme
E89X / E19X = prix moyen d'un vidéogramme
E92X / E22X = prix moyen d'un cédérom
E96X -10% <= A12 <= E96X + 10%
H11 si réponse =oui,  signaler si le champ 5 (site WEB) est non rempli
Si F17W = 0, signaler si F69X est différent de 0

A11 / C43X        = salaire moyen
F46X / F18X*100   = % desserte

E85X / E13X       = prix moyen d'un livre
E88X / E16X        = prix moyen d'un phonogramme
E91X / E19X        = prix moyen d'un vidéogramme
E94X / E22X       = prix moyen d'un cédérom
E98X -10% <= A12 <= E98X + 10%

H11 si réponse =oui,  signaler si le champ 5 (site WEB) est non rempli
Si F17W = 0, signaler si F69X est différent de 0
"""

alertes = [
('B', u"F46X / F18X*100| = % desserte               " ,"float(F46X) / int(F18X) * 100" ),
('C', u"E85X / E13X = prix moyen d'un livre         " ,"E85X / E13X    " ),
('D', u"E88X / E16X  = prix moyen d'un phonogramme  " ,"E88X / E16X    " ),
('E', u"E91X / E19X = prix moyen d'un vidéogramme   " ,"E91X / E19X    " ),
('F', u"E94X / E22X = prix moyen d'un cédérom       " ,"E94X / E22X    " ),
('G1', u"E98X - 10%" , 'int(E98X) * 0.9'),
('G2', u"A12"        , 'A12'       ),
('G3', u"E98X +10 %.", 'int(E98X) * 1.1'),
]


##############################################################################
# Controls
##############################################################################

controles = sum2controle(schema=schema)


##############################################################################
# Check that all keys are in schema
##############################################################################

def checkBDP():
    checkBib(bib_type='BDP', max=30, schema=schema)

if __name__ == '__main__':
    checkBDP()    

